apiVersion: apps/v1
kind: Deployment
metadata:
  name: formulaone-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: formulaone
  template:
    metadata:
      labels:
        app: formulaone
    spec:
      containers:
        - name: formulaone-api
          image: kennedymungai/formulaone-with-k8s
          ports:
            - containerPort: 80
              name: http-web-ai
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
